In [4]:
import numpy as np
import time

In [5]:
size=1_000_100

#for list
py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f" start and end {end-start} seconds")

#for numpy array
num_arr=np.array(py_list)
start=time.time()
sq_arr=num_arr**2
end=time.time()
print(f" start and end {end-start} seconds")


 start and end 0.16217398643493652 seconds
 start and end 0.002515077590942383 seconds


In [6]:
import sys
print(f"python list size={sys.getsizeof(py_list)*len(py_list)} bytes")
print(f"numpy array={num_arr.nbytes} bytes" )

python list size=8001656085600 bytes
numpy array=4000400 bytes


In [7]:
import numpy as np
num_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(num_arr,num_arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [7]:
import numpy as np
arr1=np.zeros((2,3),dtype="int64")
print(arr1,arr1.shape)

arr2=np.ones((2,3),dtype="int64")
print(arr2,arr2.shape)

arr3=np.full((2,3),100)
print(arr3,arr3.shape)

arr4=np.eye((3))
print(arr4,arr4.shape)

arr5=np.arange(1,10)
print(arr5,arr5.shape)

arr6=np.linspace(1,100,4)
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 2 3 4 5 6 7 8 9] (9,)
[  1.  34.  67. 100.] (4,)


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(6,)
6
int32
1
[1. 2. 3. 4. 5. 6.] float64


In [12]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshape=arr.reshape((3,2))
print(reshape,reshape.shape)
flattened=arr.flatten()
print(flattened,flattened.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [13]:
arr=np.array([1,2,3,4,5])
print(arr[1])

idx=[0,1,3]
print(arr[idx])

print(arr[arr >2])

2
[1 2 4]
[3 4 5]


In [14]:
arr=np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


In [15]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [17]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(np.sum(arr2d))
sum_of_columns=np.sum(arr2d,axis=0)
print(sum_of_columns)
sum_of_rows=np.sum(arr2d,axis=1)
print(sum_of_rows)
print(arr2d[0:1,2:4])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[3]]


In [23]:
arr3d=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3d,arr3d.shape)

#indexing
print(arr3d[0,1,1])

#slicing
print(arr3d[:,0])#first row from both layer

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]


In [25]:
#vectorization in numpy
arr=np.array([1,2,3,4,5])
arr1=np.array([6,7,8,9,10])
print(arr ** 2)
print(arr + arr1)

[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [27]:
arr=np.array([[1,2],[3,4]])
mean_arr=np.mean(arr)
standard_arr=np.std(arr)
normalized_arr=(arr-mean_arr)/standard_arr
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [32]:
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))
print(np.argmin(arr))
print(np.argmax(arr))

15
120
1
5
3.0
3.0
2.0
1.4142135623730951
0
4


In [33]:
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,3))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [34]:
arr=np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [35]:
print(np.round(3.2134))
print(np.ceil(3.12))
print(np.floor(3.94))
print(np.trunc(3.94))



3.0
4.0
3.0
3.0


In [38]:
arr=np.array([1,2,3,4,51,2,-2,-5,2])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

[-5 -2  1  2  3  4 51]
[-5 -2  1  2  2  2  3  4 51]
[ 1  2  3  4 51  2  2  5  2]
