In [1]:
#1. Import the numpy package under the name np
import numpy as np

In [2]:
#2. Print the numpy version and the configuration
print("Numpy version",np.__version__)
np.show_config()

Numpy version 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/abbur/anaconda3/Library/include
    lib directory: C:/Users/abbur/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: wind

In [3]:
#3. Create a null vector of size 10
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#4.How to find the memory size of any array
arr=np.array([1,2,3,4,5])
print(arr,np.nbytes)

[1 2 3 4 5] {<class 'numpy.bool_'>: 1, <class 'numpy.int8'>: 1, <class 'numpy.uint8'>: 1, <class 'numpy.int16'>: 2, <class 'numpy.uint16'>: 2, <class 'numpy.intc'>: 4, <class 'numpy.uintc'>: 4, <class 'numpy.int64'>: 8, <class 'numpy.uint64'>: 8, <class 'numpy.int32'>: 4, <class 'numpy.uint32'>: 4, <class 'numpy.float16'>: 2, <class 'numpy.float32'>: 4, <class 'numpy.float64'>: 8, <class 'numpy.longdouble'>: 8, <class 'numpy.complex64'>: 8, <class 'numpy.complex128'>: 16, <class 'numpy.clongdouble'>: 16, <class 'numpy.object_'>: 8, <class 'numpy.bytes_'>: 0, <class 'numpy.str_'>: 0, <class 'numpy.void'>: 0, <class 'numpy.datetime64'>: 8, <class 'numpy.timedelta64'>: 8}


In [ ]:
#5. How to get the documentation of the numpy add function from the command line
#open command prompt type python
#import numpy as np
#help(np.add)

In [6]:
#6. Create a null vector of size 10 but the fifth value which is 1
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#7. Create a vector with values ranging from 10 to 49 
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
#8.  Reverse a vector
arr=np.array([1,2,3,4,5])
reversed_arr=arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


In [16]:
#9.  Create a 3x3 matrix with values ranging from 0 to 8
arr=np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
arr=np.array([1,2,0,0,4,0])
indices=np.nonzero(arr)
print(indices)

(array([0, 1, 4], dtype=int64),)


In [20]:
#11 Create a 3x3 identity matrix
import numpy as np
arr=np.eye(3,dtype="int64")
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [21]:
#12 .Create a 3x3x3 array with random values 
import numpy as np
arr = np.random.random((3, 3, 3))
print(arr)


[[[0.91956376 0.22720243 0.67066507]
  [0.49867807 0.55224257 0.85472288]
  [0.83722073 0.86283838 0.74019995]]

 [[0.46423865 0.4939672  0.21021227]
  [0.55748657 0.39360049 0.59546603]
  [0.13728278 0.02787913 0.34019137]]

 [[0.2099391  0.22570375 0.13811981]
  [0.90503179 0.61472417 0.39455183]
  [0.3284125  0.55335457 0.90376788]]]


In [24]:
#Create a 10x10 array with random values and find the minimum and maximum values
arr=np.random.random((10,10))
print(arr)
print(arr.min())
print(arr.max())

[[0.14126688 0.18547128 0.41917423 0.18753789 0.03653679 0.20414106
  0.1580028  0.27104478 0.72078896 0.90317196]
 [0.4474566  0.77766648 0.14956111 0.66548884 0.39574389 0.81451545
  0.69352838 0.47081182 0.0839744  0.21348282]
 [0.94076073 0.83661018 0.18594901 0.16429913 0.87223679 0.19198035
  0.3832541  0.53954015 0.70170547 0.84182171]
 [0.47371802 0.09743986 0.09072051 0.7922198  0.22059681 0.48088082
  0.81629678 0.55426741 0.90762489 0.43284545]
 [0.65380453 0.669312   0.80539366 0.97502796 0.80258933 0.79348381
  0.54502124 0.21850597 0.87410451 0.95691484]
 [0.26683455 0.09152953 0.58641035 0.44376337 0.88008724 0.53786658
  0.49534494 0.50946265 0.57177248 0.81550049]
 [0.44452091 0.56181772 0.12197463 0.42535207 0.76199814 0.67763496
  0.55657712 0.19010054 0.0589051  0.9526083 ]
 [0.75885918 0.37971685 0.67370962 0.89924224 0.54416821 0.40030528
  0.83008684 0.4702466  0.61215752 0.87662683]
 [0.9910396  0.15069323 0.83765669 0.14494628 0.72334175 0.2882087
  0.67392121 

In [26]:
#14. Create a random vector of size 30 and find the mean value 
arr=np.random.rand(30)
print(arr)
print(arr.mean())

[0.63744929 0.09103739 0.3423029  0.46066057 0.29957329 0.15730704
 0.28639685 0.11324278 0.93558045 0.83277523 0.03500857 0.63967681
 0.3402789  0.68446866 0.50617691 0.24656461 0.02899241 0.42491088
 0.77901829 0.83160416 0.53669843 0.41539216 0.06588982 0.8473142
 0.11116931 0.6469617  0.45221408 0.16964288 0.76926612 0.43107762]
0.4372884100222267


In [32]:
#15.Create a 2d array with 1 on the border and 0 inside 
import numpy as np
arr = np.zeros((5, 5), dtype=int)
arr[0,:]=1
arr[-1,:]=1
arr[:,0]=1
arr[:,-1]=1
print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 0 0 0 1 1]
 [1 1 0 0 0 1 1]
 [1 1 0 0 0 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [30]:
#16. How to add a border (filled with 0's) around an existing array?
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
padding=np.pad(arr,pad_width=1,mode="constant",constant_values=0)
print(padding)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [33]:
#17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [34]:
arr = np.array([1, 2, np.nan, 4])

print(np.isnan(arr))
print(np.nanmean(arr))
print(np.nan_to_num(arr))


[False False  True False]
2.3333333333333335
[1. 2. 0. 4.]


In [35]:
np.random.seed(42)
print(np.random.rand(3))


[0.37454012 0.95071431 0.73199394]
